name: react_testing_library_dart
version: 0.1.0
author: "Keal Jones <kealjones@gmail.com>"
homepage: https://github.com/KealJones/react-testing-library-dart
description: A Dart wrapper around react-testing-library

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  js: ^0.6.1
  meta: ^1.1.7
  pedantic: any
  dart_style: '>=0.1.7 <2.0.0'

dev_dependencies:
  build_runner: ">=1.3.0 <2.0.0"
  build_web_compilers: ">=1.2.0 <3.0.0"
  test: ^1.3.4
  build_test: any

